import type { Metadata } from 'next';
import './globals.css';
import { roboto } from './ui/fonts';
import { Header } from './ui/common/Header';
import '@radix-ui/themes/styles.css';
import { Container, Theme } from '@radix-ui/themes';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Theme>
          <Container size={'3'}>
            <Header></Header>
            {children}
          </Container>
        </Theme>
      </body>
    </html>
  );
}
